apiVersion: v1
kind: Namespace
metadata:
  name: schautrack
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-deployer
  namespace: schautrack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-deployer-admin
  namespace: schautrack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: gitlab-deployer
    namespace: schautrack
