apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-creds
  namespace: schautrack
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: admin@schautrack.schauer.to
  PGADMIN_DEFAULT_PASSWORD: O2nVtZQG9w1s3GrSS2dF
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-servers
  namespace: schautrack
data:
  servers.json: |
    {
      "Servers": {
        "schautrack": {
          "Name": "Schautrack Postgres",
          "Group": "Servers",
          "Host": "schautrack-postgres.schautrack.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "schautrack",
          "SSLMode": "prefer"
        }
      }
    }
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-local-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
  claimRef:
    name: pgadmin
    namespace: schautrack
  hostPath:
    path: /var/lib/pgadmin
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin
  namespace: schautrack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: pgadmin-local-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: schautrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      securityContext:
        fsGroup: 5050
        fsGroupChangePolicy: Always
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:9.10
          envFrom:
            - secretRef:
                name: pgadmin-creds
          env:
            - name: PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED
              value: "False"
            - name: PGADMIN_SERVER_JSON_FILE
              value: /pgadmin4/servers.json
          volumeMounts:
            - name: data
              mountPath: /var/lib/pgadmin
            - name: servers
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
          ports:
            - containerPort: 80
              name: http
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
            allowPrivilegeEscalation: true
            seccompProfile:
              type: Unconfined
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pgadmin
        - name: servers
          configMap:
            name: pgadmin-servers
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: schautrack
spec:
  selector:
    app: pgadmin
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin
  namespace: schautrack
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
spec:
  ingressClassName: traefik
  rules:
    - host: pgadmin.schauer.to
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pgadmin
                port:
                  number: 80
  tls:
    - hosts:
        - pgadmin.schauer.to
