apiVersion: v1
kind: Namespace
metadata:
  name: schautrack
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
---
apiVersion: v1
kind: Secret
metadata:
  name: schautrack-app
  namespace: schautrack
type: Opaque
stringData:
  SESSION_SECRET: WFv3RzKd9ozGUEjP3eIGT3gtpXCFrSCT8hCiDA34tv6yKXouxjLy9sgSMpu1Tefj
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: schautrack-postgres-local-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
  claimRef:
    name: schautrack-postgres
    namespace: schautrack
  hostPath:
    path: /var/lib/schautrack-postgres3
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: schautrack-postgres
  namespace: schautrack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: schautrack-postgres-local-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schautrack-postgres
  namespace: schautrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schautrack-postgres
  template:
    metadata:
      labels:
        app: schautrack-postgres
    spec:
      initContainers:
        - name: fix-perms
          image: busybox:1.36
          command:
            - sh
            - -c
            - chown -R 999:999 /var/lib/postgresql/data || true
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - CHOWN
                - FOWNER
                - DAC_OVERRIDE
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      securityContext:
        fsGroup: 999
        fsGroupChangePolicy: Always
      containers:
        - name: postgres
          image: postgres:16-alpine
          envFrom:
            - secretRef:
                name: schautrack-db
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - CHOWN
                - FOWNER
                - DAC_OVERRIDE
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -h 127.0.0.1 -p 5432
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: schautrack-postgres
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: schautrack-secret-bootstrap
  namespace: schautrack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: schautrack-secret-manager
  namespace: schautrack
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: schautrack-secret-manager
  namespace: schautrack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: schautrack-secret-manager
subjects:
  - kind: ServiceAccount
    name: schautrack-secret-bootstrap
    namespace: schautrack
---
apiVersion: v1
kind: Service
metadata:
  name: schautrack-postgres
  namespace: schautrack
spec:
  selector:
    app: schautrack-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schautrack
  namespace: schautrack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: schautrack
  template:
    metadata:
      labels:
        app: schautrack
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      imagePullSecrets:
        - name: schautrack-registry
      containers:
        - name: schautrack
          image: registry.gitlab.com/florianschauer/schautrack:latest
          env:
            - name: PORT
              value: "3000"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: schautrack-db
                  key: DATABASE_URL
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: schautrack-app
                  key: SESSION_SECRET
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 3000
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: schautrack
  namespace: schautrack
spec:
  selector:
    app: schautrack
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: schautrack
  namespace: schautrack
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: schautrack
---
apiVersion: batch/v1
kind: Job
metadata:
  name: schautrack-db-secret
  namespace: schautrack
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: schautrack-secret-bootstrap
      restartPolicy: OnFailure
      containers:
        - name: secret-init
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              set -euo pipefail
              if kubectl get secret schautrack-db >/dev/null 2>&1; then
                echo "secret exists; skipping"
                exit 0
              fi
              pw="$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 48)"
              kubectl create secret generic schautrack-db \
                --from-literal=POSTGRES_DB=schautrack \
                --from-literal=POSTGRES_USER=schautrack \
                --from-literal=POSTGRES_PASSWORD="$pw" \
                --from-literal=DATABASE_URL="postgresql://schautrack:${pw}@schautrack-postgres:5432/schautrack"
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
---
apiVersion: batch/v1
kind: Job
metadata:
  name: schautrack-db-init
  namespace: schautrack
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      securityContext:
        fsGroup: 999
        fsGroupChangePolicy: Always
      containers:
        - name: db-init
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - |
              set -euo pipefail
              until pg_isready -d "$DATABASE_URL"; do
                echo "waiting for postgres..."
                sleep 2
              done
              psql "$DATABASE_URL" <<'SQL'
              CREATE TABLE IF NOT EXISTS users (
                id SERIAL PRIMARY KEY,
                email TEXT NOT NULL UNIQUE,
                password_hash TEXT NOT NULL,
                daily_goal INTEGER,
                totp_enabled BOOLEAN NOT NULL DEFAULT FALSE,
                totp_secret TEXT
              );

              CREATE TABLE IF NOT EXISTS calorie_entries (
                id SERIAL PRIMARY KEY,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                entry_date DATE NOT NULL DEFAULT CURRENT_DATE,
                amount INTEGER NOT NULL CHECK (amount >= 0)
              );

              CREATE INDEX IF NOT EXISTS calorie_entries_user_date_idx
                ON calorie_entries(user_id, entry_date);

              ALTER TABLE calorie_entries
                ADD COLUMN IF NOT EXISTS entry_name TEXT,
                ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();
              UPDATE calorie_entries SET created_at = now() WHERE created_at IS NULL;

              CREATE TABLE IF NOT EXISTS "session" (
                sid VARCHAR NOT NULL PRIMARY KEY,
                sess JSON NOT NULL,
                expire TIMESTAMP(6) NOT NULL
              );

              CREATE INDEX IF NOT EXISTS "IDX_session_expire" ON "session" ("expire");
              SQL
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: schautrack-db
                  key: DATABASE_URL
          securityContext:
            runAsUser: 999
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: schautrack
  namespace: schautrack
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
spec:
  ingressClassName: traefik
  rules:
    - host: schautrack.schauer.to
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: schautrack
                port:
                  number: 80
  tls:
    - hosts:
        - schautrack.schauer.to
