package openapi

import (
	"fmt"
	"sort"
	"strings"
)

// Markdown renders the document as a reference page.
//
// Markdown rather than a bundled Redoc/Scalar page, deliberately: those load
// their JavaScript from a CDN, which the app's Content-Security-Policy blocks,
// and vendoring a megabyte of minified JS into the repo to work around that is
// a bad trade for a document people mostly read on GitHub. The served
// openapi.json remains the machine-readable artifact — point Scalar, Bruno,
// Insomnia, or openapi-generator at it and get the interactive experience
// without the app hosting it.
func (d *Document) Markdown() string {
	var b strings.Builder

	fmt.Fprintf(&b, "# %s\n\n", d.Info.Title)
	b.WriteString("<!-- Generated by `go run ./cmd/apidocs`. Do not edit by hand:\n")
	b.WriteString("     your changes will be overwritten and CI will fail on the diff.\n")
	b.WriteString("     Edit internal/openapi/spec.go instead. -->\n\n")

	fmt.Fprintf(&b, "**Contract version %s** · OpenAPI %s · machine-readable at `GET /api/v1/openapi.json`\n\n",
		d.Info.Version, d.OpenAPI)

	if d.Info.Summary != "" {
		fmt.Fprintf(&b, "%s\n\n", d.Info.Summary)
	}

	// The Info.Description already carries the authentication, scope, error,
	// date, and pagination sections. Reuse it rather than writing a second
	// prose copy that can disagree with the served spec.
	b.WriteString(stripBuildFooter(d.Info.Description))
	b.WriteString("\n\n")

	if len(d.Servers) > 0 {
		b.WriteString("## Servers\n\n| URL | |\n| --- | --- |\n")
		for _, s := range d.Servers {
			fmt.Fprintf(&b, "| `%s` | %s |\n", s.URL, s.Description)
		}
		b.WriteString("\n")
	}

	b.WriteString(d.endpointIndex())
	b.WriteString(d.endpointReference())
	b.WriteString(d.schemaReference())

	return b.String()
}

// stripBuildFooter removes the "Served by build X" line, which is true of a
// running server but meaningless in a committed file.
func stripBuildFooter(desc string) string {
	if i := strings.Index(desc, "\n\n---\n\nServed by build"); i >= 0 {
		return desc[:i]
	}
	return desc
}

// byTag groups operations by their first tag, preserving the tag order
// declared on the document so the reference reads in a deliberate sequence
// rather than alphabetically.
func (d *Document) byTag() ([]string, map[string][]taggedOp) {
	groups := map[string][]taggedOp{}
	for path, item := range d.Paths {
		for method, op := range item.Operations() {
			tag := "Other"
			if len(op.Tags) > 0 {
				tag = op.Tags[0]
			}
			groups[tag] = append(groups[tag], taggedOp{Method: method, Path: path, Op: op})
		}
	}
	for tag := range groups {
		ops := groups[tag]
		sort.Slice(ops, func(i, j int) bool {
			if ops[i].Path != ops[j].Path {
				return ops[i].Path < ops[j].Path
			}
			return methodRank(ops[i].Method) < methodRank(ops[j].Method)
		})
	}

	var order []string
	for _, t := range d.Tags {
		if len(groups[t.Name]) > 0 {
			order = append(order, t.Name)
		}
	}
	// Anything tagged with something not declared on the document still gets
	// rendered — silently dropping an endpoint from the docs is the exact
	// failure this whole design exists to prevent.
	for tag := range groups {
		if !contains(order, tag) {
			order = append(order, tag)
		}
	}
	return order, groups
}

type taggedOp struct {
	Method string
	Path   string
	Op     *Operation
}

// methodRank orders methods read-before-write within a path.
func methodRank(m string) int {
	switch m {
	case "GET":
		return 0
	case "POST":
		return 1
	case "PUT":
		return 2
	case "PATCH":
		return 3
	case "DELETE":
		return 4
	}
	return 5
}

func contains(haystack []string, needle string) bool {
	for _, s := range haystack {
		if s == needle {
			return true
		}
	}
	return false
}

func (d *Document) endpointIndex() string {
	var b strings.Builder
	b.WriteString("## Endpoints\n\n| Endpoint | Scope | |\n| --- | --- | --- |\n")

	order, groups := d.byTag()
	for _, tag := range order {
		for _, t := range groups[tag] {
			scope := "—"
			if t.Op.Scope != "" {
				scope = "`" + t.Op.Scope + "`"
			}
			fmt.Fprintf(&b, "| [`%s %s`](#%s) | %s | %s |\n",
				t.Method, t.Path, anchor(t.Op.OperationID), scope, t.Op.Summary)
		}
	}
	b.WriteString("\n")
	return b.String()
}

func (d *Document) endpointReference() string {
	var b strings.Builder
	order, groups := d.byTag()

	for _, tag := range order {
		fmt.Fprintf(&b, "## %s\n\n", tag)
		for _, t := range d.Tags {
			if t.Name == tag && t.Description != "" {
				fmt.Fprintf(&b, "%s\n\n", t.Description)
			}
		}

		for _, t := range groups[tag] {
			op := t.Op
			fmt.Fprintf(&b, "### %s\n\n", op.Summary)
			fmt.Fprintf(&b, "```http\n%s /api/v1%s\n```\n\n", t.Method, t.Path)

			if op.Scope != "" {
				fmt.Fprintf(&b, "**Scope:** `%s`\n\n", op.Scope)
			} else if len(op.Security) == 1 && len(op.Security[0]) == 0 {
				b.WriteString("**Authentication:** none — this endpoint is public.\n\n")
			} else {
				b.WriteString("**Scope:** none beyond a valid token.\n\n")
			}

			if op.Description != "" {
				fmt.Fprintf(&b, "%s\n\n", op.Description)
			}

			if len(op.Parameters) > 0 {
				b.WriteString("| Parameter | In | Required | Description |\n| --- | --- | --- | --- |\n")
				params := append([]Parameter(nil), op.Parameters...)
				sort.SliceStable(params, func(i, j int) bool {
					// Path parameters before query parameters: they are part of
					// the URL the reader just saw.
					return params[i].In == "path" && params[j].In != "path"
				})
				for _, p := range params {
					req := ""
					if p.Required {
						req = "yes"
					}
					desc := p.Description
					if desc == "" && p.Schema != nil {
						desc = p.Schema.Description
					}
					fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", p.Name, p.In, req, desc)
				}
				b.WriteString("\n")
			}

			if op.RequestBody != nil {
				if s := bodySchemaName(op.RequestBody.Content); s != "" {
					req := "optional"
					if op.RequestBody.Required {
						req = "required"
					}
					fmt.Fprintf(&b, "**Request body** (%s): [`%s`](#%s)\n\n", req, s, anchor(s))
				}
			}

			b.WriteString("| Status | Response |\n| --- | --- |\n")
			for _, code := range sortedKeys(op.Responses) {
				resp := op.Responses[code]
				detail := resp.Description
				if s := bodySchemaName(resp.Content); s != "" {
					detail = fmt.Sprintf("[`%s`](#%s) — %s", s, anchor(s), resp.Description)
				}
				fmt.Fprintf(&b, "| `%s` | %s |\n", code, detail)
			}
			b.WriteString("\n")
		}
	}
	return b.String()
}

// bodySchemaName extracts the referenced schema name from a content map.
func bodySchemaName(content map[string]MediaType) string {
	for _, mt := range content {
		if mt.Schema == nil {
			continue
		}
		if name, ok := strings.CutPrefix(mt.Schema.Ref, "#/components/schemas/"); ok {
			return name
		}
	}
	return ""
}

func (d *Document) schemaReference() string {
	var b strings.Builder
	b.WriteString("## Schemas\n\n")

	for _, name := range sortedKeys(d.Components.Schemas) {
		s := d.Components.Schemas[name]
		fmt.Fprintf(&b, "### %s\n\n", name)
		if s.Description != "" {
			fmt.Fprintf(&b, "%s\n\n", s.Description)
		}
		if len(s.Properties) == 0 {
			b.WriteString("Free-form object; see `GET /api/v1/openapi.json` for the served shape.\n\n")
			continue
		}

		writeFieldTable(&b, s, "")
	}
	return b.String()
}

// writeFieldTable renders one schema's fields, then recurses into any property
// that is an inline object with properties of its own.
//
// Without the recursion a nested object printed as the single word `object` and
// its fields appeared nowhere in the document (#393). Me was the worst case: its
// user, token, server and features objects carry most of what the endpoint
// returns, and the Markdown said nothing about any of them. A $ref is different
// — typeName already links to that component's own section — so only inline
// objects are expanded here.
//
// prefix carries the dotted path so the sub-table has a heading a reader can
// match to the parent row ("Me.user"), and so two schemas with a `user` object
// do not produce two identically titled sections.
func writeFieldTable(b *strings.Builder, s *Schema, prefix string) {
	required := map[string]bool{}
	for _, r := range s.Required {
		required[r] = true
	}

	b.WriteString("| Field | Type | Required | Description |\n| --- | --- | --- | --- |\n")
	for _, field := range sortedKeys(s.Properties) {
		p := s.Properties[field]
		req := ""
		if required[field] {
			req = "yes"
		}
		fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n", field, typeName(p), req, p.Description)
	}
	b.WriteString("\n")

	for _, field := range sortedKeys(s.Properties) {
		p := s.Properties[field]
		if p == nil || p.Ref != "" || len(p.Properties) == 0 {
			continue
		}
		path := field
		if prefix != "" {
			path = prefix + "." + field
		}
		fmt.Fprintf(b, "#### %s\n\n", path)
		if p.Description != "" {
			fmt.Fprintf(b, "%s\n\n", p.Description)
		}
		writeFieldTable(b, p, path)
	}
}

// typeName renders a schema's type for the docs table, including references,
// arrays, and the ["integer","null"] unions OpenAPI 3.1 uses for nullability.
func typeName(s *Schema) string {
	if s == nil {
		return ""
	}
	if name, ok := strings.CutPrefix(s.Ref, "#/components/schemas/"); ok {
		return fmt.Sprintf("[`%s`](#%s)", name, anchor(name))
	}
	if len(s.AnyOf) > 0 {
		var parts []string
		for _, alt := range s.AnyOf {
			parts = append(parts, typeName(alt))
		}
		return strings.Join(parts, " or ")
	}
	// An enum renders as its members, not as the type they happen to share.
	// "string" tells a reader nothing they could not have guessed; `kg` | `lb`
	// is the entire contract of the field (#363). Checked before the type
	// switch so it wins for every underlying type, not just string.
	if len(s.Enum) > 0 {
		var parts []string
		for _, v := range s.Enum {
			if v == nil {
				parts = append(parts, "`null`")
				continue
			}
			parts = append(parts, fmt.Sprintf("`%v`", v))
		}
		return strings.Join(parts, " \\| ")
	}
	switch t := s.Type.(type) {
	case string:
		if t == "array" {
			return "array of " + typeName(s.Items)
		}
		if s.Format != "" {
			return fmt.Sprintf("`%s` (%s)", t, s.Format)
		}
		return "`" + t + "`"
	case []string:
		var parts []string
		for _, one := range t {
			parts = append(parts, "`"+one+"`")
		}
		return strings.Join(parts, " or ")
	}
	return "`object`"
}

// anchor converts a heading to the GitHub-style fragment id it will get.
func anchor(s string) string {
	s = strings.ToLower(s)
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == ' ', r == '-', r == '_':
			b.WriteRune('-')
		}
	}
	return b.String()
}

func sortedKeys[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
