-- Schautrack database schema — INTENTIONALLY CONTAINS NO DDL.
--
-- The full schema (every table, index, and constraint — including the
-- "session" table) is created and kept up to date by the application itself
-- at startup: the ensureXxxSchema() migrations in
-- internal/database/migrations.go are the single source of truth. They run
-- sequentially under a Postgres advisory lock and fully initialize an empty
-- database before the server accepts traffic.
--
-- A previous version of this file duplicated part of that schema and had
-- drifted: fresh installs got doubled constraints (inline UNIQUE next to the
-- migrations' named unique indexes, inline CHECK next to
-- calorie_entries_amount_range), and five tables (ai_usage,
-- user_oidc_accounts, user_passkeys, saved_foods, audit_log) were missing
-- entirely. Rather than maintain the schema in two places, the DDL was
-- removed. Production (compose.yml) and E2E (compose.test.yml) never mounted
-- this file — those environments have always initialized from the app
-- migrations alone. compose.dev.yml no longer mounts it either.
--
-- To change the schema, add or extend a migration in
-- internal/database/migrations.go.
